# Generated by Django 5.0.6 on 2024-05-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_category_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='number_of_ratings',
            field=models.IntegerField(default=0, verbose_name='Количество оценок'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_rating',
            field=models.IntegerField(default=0, verbose_name='Суммарный рейтинг'),
        ),
    ]
