# Generated by Django 5.0.6 on 2024-05-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='comments_photos/', verbose_name='Фото комментария'),
        ),
    ]
